id = "lsmock"
name = "Mock language server integration"
version = "0.0.1"
schema_version = 1
authors = ["Vlad Minaev <vlad.minaev@gmail.com>"]
description = "Integrates "
repository = "https://github.com/web-devel/lsmock"
